### ISSUE TITLE
Ambiguous class [class name] resolution

### ISSUE THREAD

**Issue by nvaken** [palantirnet/drupal-rector#126]
I'm not sure if I'm expecting too much from drupal-rector, but when trying to process a custom module I get errors about another module. In this case the other module is ckeditor and the process is unable to continue. I'm not even sure if this error is related to D9 compatibility or just a error on ckeditor, but I expected not being disturbed by an error on tests like this. Should I adjust my expectations? Is this a bug in rector? Am I doing something wrong? 

I'm using the default "web" `rector.yml` file. 

```
vendor/bin/rector process /web/modules/custom/my_module --dry-run
```

```
Rector v0.7.29
Config file: rector.yml

In RobotLoader.php line 186:
  Ambiguous class Drupal\Tests\ckeditor\FunctionalJavascript\ToolbarButtonsTest resolution; defined in web/core/core/modules/ckeditor/tests/src/FunctionalJavascript/ToolbarButtonsTest.php and in web/core/tests/src/FunctionalJavascript/ToolbarButtonsTest.php.
```

**Comment by damontgomery** [comment]
Sorry for the issues and thanks for the feedback.

You may be able to bypass this issue by uncommenting a few optional lines in the configuration file which will ignore test files.

https://github.com/palantirnet/drupal-rector/blob/master/rector.yml

```
parameters:
  autoload_paths:
    - 'web/core'
    - 'web/core/modules'
    - 'web/modules'
    - 'web/profiles'

  exclude_paths:
    # This path is used by the upgrade_status module.
    - '*/upgrade_status/tests/modules/*'
    # If you would like to skip test directories, uncomment the following lines:
    # - '*/tests/*'
    # - '*/Tests/*'
```

I think what you're doing makes sense, just running it on your module folder.

Rector tries to load classes, but not sure why it's trying to load classes for these other modules that aren't related to your code. Since that other module is in core, I would think our automated tests here would fail if it was a universal problem.

Can you try uncommenting those lines mentioned?
